/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/model/habitacion.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./model/habitacion.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.698, 0.027, 2.62]} rotation={[0, -1.223, 0]} scale={0.011}>
        <group position={[0, 0.426, 0]}>
          <group position={[0, 27.827, 0]}>
            <mesh geometry={nodes.base_sticks_geom.geometry} material={nodes.base_sticks_geom.material} position={[0, -27.827, 0]} />
          </group>
          <group position={[0, 8.71, -0.025]}>
            <mesh geometry={nodes.bottom_sticks_geom.geometry} material={nodes.bottom_sticks_geom.material} position={[-12.435, 0, 6.385]} />
          </group>
          <group position={[0, 23.559, 0]}>
            <mesh geometry={nodes.frame_geom.geometry} material={nodes.frame_geom.material} position={[0, 20.907, 0]} />
          </group>
          <group position={[0, 14.969, 0]}>
            <mesh geometry={nodes.low_connectors_row_geom.geometry} material={nodes.low_connectors_row_geom.material} position={[0, -14.969, 0]} />
          </group>
          <group position={[0, 31.174, 0]}>
            <mesh geometry={nodes.middle_connectors_row_geom.geometry} material={nodes.middle_connectors_row_geom.material} position={[0, -31.174, 0]} />
          </group>
          <group position={[0, 44.447, 0]}>
            <mesh geometry={nodes.top_connectors_row_geom.geometry} material={nodes.top_connectors_row_geom.material} position={[0, -44.447, 0]} />
          </group>
          <mesh geometry={nodes.bottom_coonectros_row_geom.geometry} material={nodes.bottom_coonectros_row_geom.material} />
        </group>
        <mesh geometry={nodes.towels.geometry} material={nodes.towels.material} position={[0, 0.426, 0]} />
      </group>
      <group position={[-0.763, 1.282, -2.741]} rotation={[Math.PI, -1.555, Math.PI]} scale={0.002}>
        <mesh geometry={nodes.bolts.geometry} material={nodes.bolts.material} position={[-0.019, 158.819, 7.809]} />
        <mesh geometry={nodes.glass.geometry} material={nodes.glass.material} position={[-0.079, -302.505, 13.307]} />
        <mesh geometry={nodes.leg001.geometry} material={nodes.leg001.material} position={[-0.254, -321.27, 8.829]} />
        <mesh geometry={nodes.logo.geometry} material={nodes.logo.material} position={[-0.006, -289.745, 23.656]} />
        <mesh geometry={nodes.main_body.geometry} material={materials['Material.002']} position={[0, 15.237, -5.097]} />
        <mesh geometry={nodes.metal.geometry} material={nodes.metal.material} position={[-0.081, -299.836, 13.338]} />
        <mesh geometry={nodes.object.geometry} material={nodes.object.material} position={[-0.121, -302.675, 13.803]} />
        <mesh geometry={nodes.rubbers.geometry} material={nodes.rubbers.material} position={[-260.568, -334.3, -82.646]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.screen.geometry} material={materials['Material.002']} position={[0, 25.829, 23.164]} />
        <mesh geometry={nodes.upper_metal.geometry} material={nodes.upper_metal.material} position={[0, 19.501, 17.949]} />
      </group>
      <mesh geometry={nodes.Carpet001.geometry} material={materials['Material.001']} position={[-1.408, 0.056, -2.826]} rotation={[Math.PI, 0, Math.PI]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.Carpet003.geometry} material={materials['Material.001']} position={[-1.408, 0.056, 1.127]} rotation={[Math.PI, 0, Math.PI]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.Carpet004.geometry} material={materials['Material.001']} position={[-4.74, 0.056, 1.127]} rotation={[Math.PI, 0, Math.PI]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.Carpet005.geometry} material={materials['Material.014']} position={[-0.193, 1.598, 1.127]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.Carpet006.geometry} material={materials['Material.014']} position={[-0.193, 1.598, -2.852]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.Carpet007.geometry} material={materials['Material.014']} position={[-4.457, 1.598, -4.783]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.Carpet008.geometry} material={materials['Material.014']} position={[-6.42, 1.598, -2.852]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.Carpet009.geometry} material={materials['Material.014']} position={[-6.419, 1.598, 1.127]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.Mesh283.geometry} material={materials['Material.012']} position={[-3.714, 0.161, 1.077]} scale={0.006} />
      <mesh geometry={nodes.Mesh283001.geometry} material={materials['Material.013']} position={[-3.724, 0.161, 0.786]} rotation={[Math.PI, -0.753, Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Mesh286.geometry} material={nodes.Mesh286.material} position={[-3.716, 0.342, 1.053]} scale={0.006} />
      <mesh geometry={nodes.Mesh286001.geometry} material={nodes.Mesh286001.material} position={[-3.706, 0.342, 0.803]} rotation={[Math.PI, -0.753, Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Mesh290.geometry} material={materials['Material.013']} position={[-3.693, 0.161, 1.016]} scale={0.006} />
      <mesh geometry={nodes.Mesh290001.geometry} material={nodes.Mesh290001.material} position={[-3.697, 0.161, 0.845]} rotation={[Math.PI, -0.753, Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Mesh293.geometry} material={nodes.Mesh293.material} position={[-3.71, 0.342, 1.034]} scale={0.006} />
      <mesh geometry={nodes.Mesh293001.geometry} material={nodes.Mesh293001.material} position={[-3.698, 0.342, 0.82]} rotation={[Math.PI, -0.753, Math.PI]} scale={0.006} />
      <mesh geometry={nodes.Mesh297.geometry} material={nodes.Mesh297.material} position={[-3.703, 0.124, 1.047]} scale={0.006} />
      <mesh geometry={nodes.Mesh297001.geometry} material={materials['Material.013']} position={[-3.711, 0.124, 0.815]} rotation={[Math.PI, -0.753, Math.PI]} scale={0.006} />
      <group position={[-6.131, 0.04, 0.565]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh geometry={nodes['3d-model001_1'].geometry} material={nodes['3d-model001_1'].material} />
        <mesh geometry={nodes['3d-model001_2'].geometry} material={nodes['3d-model001_2'].material} />
      </group>
      <mesh geometry={nodes.Cross_Shoelace.geometry} material={nodes.Cross_Shoelace.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace001.geometry} material={nodes.Cross_Shoelace001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace_2.geometry} material={nodes.Cross_Shoelace_2.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace_2001.geometry} material={nodes.Cross_Shoelace_2001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace_3.geometry} material={nodes.Cross_Shoelace_3.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace_3001.geometry} material={nodes.Cross_Shoelace_3001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace_4.geometry} material={nodes.Cross_Shoelace_4.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace_4001.geometry} material={nodes.Cross_Shoelace_4001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace_5.geometry} material={nodes.Cross_Shoelace_5.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Cross_Shoelace_5001.geometry} material={nodes.Cross_Shoelace_5001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc.geometry} material={nodes.Disc.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_1.geometry} material={nodes.Disc_1.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_10.geometry} material={nodes.Disc_10.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_10001.geometry} material={nodes.Disc_10001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_11.geometry} material={nodes.Disc_11.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_11001.geometry} material={nodes.Disc_11001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_12.geometry} material={nodes.Disc_12.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_12001.geometry} material={nodes.Disc_12001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_13.geometry} material={nodes.Disc_13.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_2.geometry} material={nodes.Disc_2.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_3.geometry} material={nodes.Disc_3.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_4.geometry} material={nodes.Disc_4.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_5.geometry} material={nodes.Disc_5.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_6.geometry} material={nodes.Disc_6.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_7.geometry} material={nodes.Disc_7.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_7001.geometry} material={nodes.Disc_7001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_8.geometry} material={nodes.Disc_8.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_8001.geometry} material={nodes.Disc_8001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_9.geometry} material={nodes.Disc_9.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Disc_9001.geometry} material={nodes.Disc_9001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Inner.geometry} material={nodes.Inner.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Inner001.geometry} material={nodes.Inner001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race.geometry} material={nodes.race.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race007.geometry} material={nodes.race007.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race008.geometry} material={nodes.race008.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race009.geometry} material={nodes.race009.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race010.geometry} material={nodes.race010.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race011.geometry} material={nodes.race011.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race1.geometry} material={nodes.race1.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race2.geometry} material={nodes.race2.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race3.geometry} material={nodes.race3.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race4.geometry} material={nodes.race4.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.race5.geometry} material={nodes.race5.material} position={[-6.018, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Shoe.geometry} material={nodes.Shoe.material} position={[-6.09, 0.023, 0.019]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Shoe001.geometry} material={nodes.Shoe001.material} position={[-6.018, 0.023, -0.166]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Carpet002.geometry} material={materials['Material.001']} position={[-4.731, 0.056, -2.835]} rotation={[Math.PI, 0, Math.PI]} scale={[1.667, 0.507, 1.989]} />
      <mesh geometry={nodes.FlexformFeelGoodBed3.geometry} material={materials['Material.009']} position={[-3.712, 0.663, -2.78]} rotation={[Math.PI / 2, 0, 0.013]} scale={0.015} />
      <mesh geometry={nodes.FlexformFeelGoodBed4.geometry} material={materials['Material.008']} position={[-4.605, 0.581, -2.861]} rotation={[Math.PI / 2, 0, 0.013]} scale={0.015} />
      <mesh geometry={nodes.FlexformFeelGoodBed5.geometry} material={materials['Material.010']} position={[-4.72, 0.535, -2.782]} rotation={[Math.PI / 2, 0, 0.013]} scale={0.015} />
      <mesh geometry={nodes.FlexformFeelGoodBed6.geometry} material={nodes.FlexformFeelGoodBed6.material} position={[-5.895, 0.924, -2.794]} rotation={[Math.PI / 2, 0, 0.013]} scale={0.015} />
      <mesh geometry={nodes.Plane085.geometry} material={nodes.Plane085.material} position={[-4.718, 0.372, -2.891]} rotation={[0, 1.571, 0]} />
      <group position={[-4.721, 0.796, -2.506]} rotation={[Math.PI, -0.678, Math.PI]} scale={[0.195, 0.277, 0.277]}>
        <mesh geometry={nodes.Plane220.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Plane220_1.geometry} material={nodes.Plane220_1.material} />
        <group position={[-1.035, 0.676, -0.061]} rotation={[0, 0, -Math.PI]} scale={[0.016, 0.685, 0.972]}>
          <mesh geometry={nodes.Cube100.geometry} material={nodes.Cube100.material} />
          <mesh geometry={nodes.Cube100_1.geometry} material={materials['Material.002']} />
          <group position={[-1.177, -0.97, 0.065]} rotation={[0, 0, 1.571]} scale={[0.071, 0.628, 0.05]}>
            <mesh geometry={nodes.Cylinder069.geometry} material={nodes.Cylinder069.material} />
            <mesh geometry={nodes.Cylinder069_1.geometry} material={nodes.Cylinder069_1.material} />
          </group>
          <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-1.971, 0.959, -0.809]} rotation={[Math.PI, 0, 0]} scale={[12.669, 0.226, 0.16]} />
        </group>
        <mesh geometry={nodes.Cube077.geometry} material={nodes.Cube077.material} position={[0.088, -0.008, 0.189]} scale={[0.086, 0.008, 0.287]} />
      </group>
      <mesh geometry={nodes.Circle070.geometry} material={nodes.Circle070.material} position={[-0.501, 0.012, -0.979]} rotation={[Math.PI, 0, Math.PI]} scale={[0.047, 0.058, 0.047]} />
      <mesh geometry={nodes.Circle092.geometry} material={nodes.Circle092.material} position={[-0.74, 0.035, -1.117]} rotation={[Math.PI, 0, Math.PI]} scale={0.055} />
      <mesh geometry={nodes.Circle093.geometry} material={nodes.Circle093.material} position={[-1.149, 0.017, -0.821]} rotation={[Math.PI, 0, Math.PI]} scale={0.066} />
      <mesh geometry={nodes.Cylinder043.geometry} material={nodes.Cylinder043.material} position={[-1.156, 0.82, -0.889]} rotation={[3.092, 0, Math.PI]} scale={[0.004, 0.46, 0.004]} />
      <mesh geometry={nodes.Cylinder044.geometry} material={nodes.Cylinder044.material} position={[-1.125, 0.818, -0.729]} rotation={[0.101, 0.325, -0.063]} scale={[0.004, 0.518, 0.004]} />
      <mesh geometry={nodes.Cylinder045.geometry} material={nodes.Cylinder045.material} position={[-1.128, 0.818, -0.792]} rotation={[2.953, 1.382, -2.999]} scale={[0.003, 0.415, 0.003]} />
      <mesh geometry={nodes.Cylinder046.geometry} material={nodes.Cylinder046.material} position={[-1.118, 0.82, -0.853]} rotation={[0.072, -0.816, 0.052]} scale={[0.003, 0.472, 0.003]} />
      <mesh geometry={nodes.Cylinder047.geometry} material={nodes.Cylinder047.material} position={[-1.061, 0.818, -0.833]} rotation={[2.925, 1.11, -2.978]} scale={[0.004, 0.481, 0.004]} />
      <mesh geometry={nodes.Cylinder048.geometry} material={nodes.Cylinder048.material} position={[-1.2, 0.82, -0.776]} rotation={[0.067, -0.752, 0.046]} scale={[0.004, 0.708, 0.004]} />
      <mesh geometry={nodes.Cylinder049.geometry} material={nodes.Cylinder049.material} position={[-1.158, 0.82, -0.753]} rotation={[0.049, -0.044, 0.002]} scale={[0.003, 0.65, 0.003]} />
      <mesh geometry={nodes.Cylinder050.geometry} material={nodes.Cylinder050.material} position={[-1.096, 0.818, -0.876]} rotation={[3.037, 0.409, -3.131]} scale={[0.003, 0.441, 0.003]} />
      <mesh geometry={nodes.Cylinder051.geometry} material={nodes.Cylinder051.material} position={[-1.208, 0.82, -0.77]} rotation={[0.119, -1.145, 0.109]} scale={[0.003, 0.357, 0.003]} />
      <mesh geometry={nodes.Cylinder052.geometry} material={nodes.Cylinder052.material} position={[-1.118, 0.818, -0.807]} rotation={[3.097, 0.676, 3.128]} scale={[0.003, 0.381, 0.003]} />
      <mesh geometry={nodes.Cylinder053.geometry} material={nodes.Cylinder053.material} position={[-1.078, 0.818, -0.765]} rotation={[0.186, 1.028, -0.19]} scale={[0.004, 0.475, 0.004]} />
      <mesh geometry={nodes.Cylinder054.geometry} material={nodes.Cylinder054.material} position={[-1.196, 0.82, -0.857]} rotation={[3.077, -0.708, 3.099]} scale={[0.004, 0.699, 0.004]} />
      <mesh geometry={nodes.Cylinder055.geometry} material={nodes.Cylinder055.material} position={[-1.084, 0.818, -0.833]} rotation={[2.97, 0.978, -3.03]} scale={[0.004, 0.592, 0.004]} />
      <mesh geometry={nodes.Cylinder056.geometry} material={nodes.Cylinder056.material} position={[-1.195, 0.82, -0.809]} rotation={[0.093, 1.011, -0.079]} scale={[0.003, 0.541, 0.003]} />
      <mesh geometry={nodes.Cylinder057.geometry} material={nodes.Cylinder057.material} position={[-1.145, 0.82, -0.735]} rotation={[0.049, -0.027, 0.001]} scale={[0.003, 0.502, 0.003]} />
      <mesh geometry={nodes.Cylinder058.geometry} material={nodes.Cylinder058.material} position={[-1.181, 0.82, -0.835]} rotation={[0.052, 0.303, -0.015]} scale={[0.003, 0.589, 0.003]} />
      <mesh geometry={nodes.Cylinder059.geometry} material={nodes.Cylinder059.material} position={[-1.072, 0.818, -0.775]} rotation={[0.664, 1.415, -0.689]} scale={[0.004, 0.646, 0.004]} />
      <mesh geometry={nodes['default'].geometry} material={materials['Material.006']} position={[-5.115, 0.653, 2.015]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={0.011} />
      <mesh geometry={nodes.default0011.geometry} material={materials['Material.005']} position={[-5.227, 0.855, 2.077]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={0.011} />
      <mesh geometry={nodes.default00133.geometry} material={materials['Material.007']} position={[-4.484, 0.416, 1.996]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={0.011} />
      <mesh geometry={nodes.Object001.geometry} material={materials['Material.005']} position={[-5.338, 0.89, 2.256]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={0.011} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.004']} position={[-5.069, 0.548, 1.973]} rotation={[-Math.PI, 0.69, -Math.PI]} scale={[0.011, 0.013, 0.011]} />
      <group position={[-0.829, 0.371, -2.73]} rotation={[-Math.PI, 0.016, -Math.PI]} scale={1.284}>
        <mesh geometry={nodes.Cube093.geometry} material={nodes.Cube093.material} />
        <mesh geometry={nodes.Cube093_1.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/habitacion.glb')
