/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/model/untitled.glb 
*/

//import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {ThreeElements } from '@react-three/fiber'

export function Model(props:ThreeElements['group']) {
  const { nodes, materials } = useGLTF('./model/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={materials['Material.001']} position={[0, 2.913, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} position={[0, 0, -3.593]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/untitled.glb')
